# Dataframe

Un objeto del tipo `DataFrame` define un conjunto de datos estructurado en forma de tabla donde cada columna es un objeto de tipo `Series`. En general, todos los datos de una misma columna son del mismo tipo, y las filas son registros que pueden contender datos de distintos tipos.

Un `DataFrame` contiene dos índices, uno para las *filas* y otro para las *columnas*, y se puede acceder a sus elementos mediante los nombres de las filas y las columnas.

## Creación de un DataFrame

In [ ]:
import pandas as pd

In [ ]:
dataframe = pd.DataFrame({'A': [1, 2, 3]})
pd.DataFrame({'A': [1, 2, 3]})
print(dataframe)

### Creación de un DataFrame a partir de un diccionario de listas

Para crear un `DataFrame` a partir de un diccionario cuyas claves son los nombres de las columnas y los valores son listas con los datos de las columnas se utiliza el método:

```python
pd.Dataframe(data=diccionario, index=filas, columns=columnas, dtype=tipos)
```

* Devuelve un objeto del tipo DataFrame cuyas columnas son las listas contenidas en los valores del diccionario `diccionario`,
  
* Los nombres de filas son los indicados en la lista `filas`,

* Los nombres de columnas son los indicados en la lista `columnas` y los tipos indicados en la lista tipos.

* La lista `filas` tiene que tener el mismo tamaño que las listas del diccionario, mientras que las listas `columnas` y tipos tienen que tener el mismo tamaño que el diccionario.
  
* Si no se pasa la lista de filas se utilizan como nombres los enteros empezando en 0. Si no se pasa la lista de columnas se utilizan como nombres las claves del diccionario. Si no se pasa la lista de tipos, se infiere.

**Observación:** Los valores asociados a las claves del diccionario deben ser listas del mismo tamaño.

In [ ]:
import pandas as pd
datos = {'Nombre':['María', 'Luis', 'Carmen', 'Antonio'],
         'Edad':[18, 22, 20, 21],
         'Carrera':['Economía', 'Medicina', 'Arquitectura', 'Economía'],
         'Correo':['maria@gmail.com', 'luis@yahoo.es', 'carmen@gmail.com', 'antonio@gmail.com']
         }
df = pd.DataFrame(datos)
df
#print(df)

In [ ]:
# @title Edad

from matplotlib import pyplot as plt
df['Edad'].plot(kind='hist', bins=20, title='Edad')
plt.gca().spines[['top', 'right',]].set_visible(False)

### Creación de un DataFrame a partir de una listas de listas

Para crear un `DataFrame` a **partir de una lista de listas** con los datos de las columnas se utiliza el siguiente método:

`pd.Dataframe(data=listas, index=filas, columns=columnas, dtype=tipos)`

* Devuelve un objeto del tipo `DataFrame` cuyas columnas son los valores de las listas de la lista listas,

* Los nombres de filas indicados en la lista `filas`, los nombres de columnas indicados en la lista `columnas` y los tipos indicados en la lista tipos.
  
* La lista `filas`, tiene que tener el mismo tamaño que la lista listas mientras que las listas `columnas` y tipos tienen que tener el mismo tamaño que las listas anidadas en `listas`.
  
* Si no se pasa la lista de `filas` o de `columnas` se utilizan enteros empezando en 0. Si no se pasa la lista de tipos, se infiere.

**Observación:** Si las listas anidadas en listas no tienen el mismo tamaño, las listas menores se rellenan con valores `NaN`.

In [ ]:
import pandas as pd
df = pd.DataFrame([['María', 18, 'Economia'], ['Luis', 22, 'Actuaria'], ['Carmen', 20]], columns=['Nombre', 'Edad', 'Carrera'])
print(df)

### Creación de un DataFrame a partir de una lista de diccionarios

Para crear un DataFrame a partir de una lista de diccionarios con los datos de las filas, se utiliza el siguiente método:

`pd.Dataframe(data=diccionarios, index=filas, columns=columnas, dtype=tipos)`

* Devuelve un objeto del tipo DataFrame cuyas filas contienen los valores de los diccionarios de la lista diccionarios,

* Los nombres de filas indicados en la lista filas, los nombres de columnas indicados en la lista columnas y los tipos indicados en la lista tipos.

* La lista filas tiene que tener el mismo tamaño que la lista lista. Si no se pasa la lista de filas se utilizan enteros empezando en 0.
  
* Si no se pasa la lista de columnas se utilizan las claves de los diccionarios.

**Observación:** Si no se pasa la lista de tipos, se infiere. Si los diccionarios no tienen las mismas claves, las claves que no aparecen en el diccionario se rellenan con valores `NaN`.

In [ ]:
import pandas as pd
df = pd.DataFrame([{'Nombre':'María', 'Edad':18}, {'Edad':22, 'Nombre':'Luis', }, {'Nombre':'Carmen'}])
print(df)

### Creación de un DataFrame a partir de un array

Para crear un DataFrame a partir de un `array` de NumPy se utiliza el siguiente método:

`pd.Dataframe(data=array, index=filas, columns=columnas, dtype=tipo)`

* Devuelde un objeto del tipo `DataFrame` cuyas filas y columnas son las del array `array`,

* Los nombres de filas indicados en la lista `filas`, los nombres de columnas indicados en la lista `columnas` y el tipo indicado en tipo.
  
* La lista `filas` tiene que tener el mismo tamaño que el número de filas del array y la lista `columnas` el mismo tamaño que el número de columnas del `array`.
  
<!-- * Si no se pasa la lista de `filas` se utilizan enteros empezando en 0. Si no se pasa la lista de `columnas` se utilizan las claves de los diccionarios. Si no se pasa la lista de tipos, se infiere. -->

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(4, 3), columns=['a', 'b', 'c'])
df

### Creación de un DataFrame a partir de un fichero CSV o Excel

Dependiendo del tipo de fichero, existen distintas funciones para importar un DataFrame desde un fichero.

```python
read_csv(fichero.csv, sep=separador, header=n, index_col=m, na_values=no-validos, decimal=separador-decimal)
```

* Devuelve un objeto del tipo DataFrame con los datos del fichero CSV `fichero.csv`

* Se usan como separador de los datos la cadena `separador`.

* Como nombres de columnas se utiliza los valores de la fila `n` y como nombres de filas los valores de la columna `m`.
  
*  Si no se indica `m` se utilizan como nombres de filas los enteros empezando en 0.
  
* Los valores incluídos en la lista no-validos se convierten en `NaN`.
  
* Para los datos numéricos se utiliza como separador de decimales el carácter indicado en `separador-decimal`.

```python
read_excel(fichero.xlsx, sheet_name=hoja, header=n, index_col=m, na_values=no-validos, decimal=separador-decimal)
```

* Devuelve un objeto del tipo `DataFrame` con los datos de la hoja de cálculo hoja del fichero Excel `fichero.xlsx`.
  
* Como nombres de columnas se utiliza los valores de la fila n y como nombres de filas los valores de la columna m.
  
* Si no se indica m se utilizan como nombres de filas los enteros empezando en 0. Los valores incluídos en la lista no-validos se convierten en NaN. Para los datos numéricos se utiliza como separador de decimales el carácter indicado en separador-decimal.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal='.')
df

In [ ]:
df.head(2)

In [ ]:
df.tail(3)

In [ ]:
df.info()

In [ ]:
df.shape

In [ ]:
df.size

In [ ]:
df.columns

In [ ]:
df.index

El archivo CSV del Titanic generalmente contiene varias columnas que representan diferentes características de los pasajeros. A continuación se detallan las columnas más comunes y su significado:

El archivo CSV del Titanic generalmente contiene varias columnas que representan diferentes características de los pasajeros. A continuación se detallan las columnas más comunes y su significado:

- **PassengerId**: Un identificador único para cada pasajero.

- **Survived**: Indica si el pasajero sobrevivió (1) o no (0).

- **Pclass**: Clase del pasajero (1 = 1ª clase, 2 = 2ª clase, 3 = 3ª clase).

- **Name**: Nombre del pasajero.

- **Sex**: Género del pasajero (male = hombre, female = mujer).

- **Age**: Edad del pasajero.

- **SibSp**: Número de hermanos/esposos a bordo del Titanic.

- **Parch**: Número de padres/hijos a bordo del Titanic.

- **Ticket**: Número del billete del pasajero.

- **Fare**: Tarifa pagada por el billete.

- **Cabin**: Número de cabina del pasajero.

- **Embarked**: Puerto de embarque del pasajero (C = Cherburgo; Q = Queenstown; S = Southampton).

In [ ]:
import pandas as pd
df  = pd.read_csv('/content/colesterol.csv', sep = ',',decimal='.')
df

In [ ]:
# @title Age

from matplotlib import pyplot as plt
df['Survived'].plot(kind='hist', bins=20, title='Survived')
plt.gca().spines[['top', 'right',]].set_visible(False)

In [ ]:
# @title Survived vs Pclass

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='Survived', y='Pclass', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

In [ ]:
# @title Embarked

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Embarked').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

In [ ]:
# @title Age

from matplotlib import pyplot as plt
df['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

## Atributos de un `Dataframe`

<center>
<table>
  <tr>
    <th>Atributo</th>
    <th>Descripción</th>
    <th>Ejemplo de Uso</th>
  </tr>
  <tr>
    <td>shape</td>
    <td>Devuelve una tupla con el número de filas y columnas del DataFrame</td>
    <td>df.shape</td>
  </tr>
  <tr>
    <td>columns</td>
    <td>Devuelve una lista con los nombres de las columnas del DataFrame</td>
    <td>df.columns</td>
  </tr>
  <tr>
    <td>index</td>
    <td>Devuelve el índice (etiquetas de fila) del DataFrame</td>
    <td>df.index</td>
  </tr>
  <tr>
    <td>values</td>
    <td>Devuelve una matriz NumPy que representa los datos del DataFrame</td>
    <td>df.values</td>
  </tr>
  <tr>
    <td>dtypes</td>
    <td>Devuelve los tipos de datos de cada columna del DataFrame</td>
    <td>df.dtypes</td>
  </tr>
  <tr>
    <td>info()</td>
    <td>Proporciona información sobre el DataFrame, incluyendo el número total de entradas no nulas por columna y el tipo de datos de cada columna</td>
    <td>df.info()</td>
  </tr>
  <tr>
    <td>describe()</td>
    <td>Calcula estadísticas descriptivas para las columnas numéricas del DataFrame</td>
    <td>df.describe()</td>
  </tr>
  <tr>
    <td>head(n)</td>
    <td>Devuelve las primeras n filas del DataFrame</td>
    <td>df.head()</td>
  </tr>
  <tr>
    <td>tail(n)</td>
    <td>Devuelve las últimas n filas del DataFrame</td>
    <td>df.tail()</td>
  </tr>
  <tr>
    <td>T</td>
    <td>Devuelve una transposición del DataFrame, intercambiando filas y columnas</td>
    <td>df.T</td>
  </tr>
  <tr>
    <td>empty</td>
    <td>Devuelve un valor booleano que indica si el DataFrame está vacío</td>
    <td>df.empty</td>
  </tr>
  <tr>
    <td>ndim</td>
    <td>Devuelve el número de dimensiones del DataFrame</td>
    <td>df.ndim</td>
  </tr>
  <tr>
    <td>size</td>
    <td>Devuelve el número total de elementos en el DataFrame</td>
    <td>df.size</td>
  </tr>
  <tr>
    <td>style</td>
    <td>Permite aplicar estilos a un DataFrame para resaltar visualmente los datos</td>
    <td>df.style</td>
  </tr>
  <tr>
    <td>nunique()</td>
    <td>Devuelve el número de valores únicos en cada columna</td>
    <td>df['columna'].nunique()</td>
  </tr>
  <tr>
    <td>unique()</td>
    <td>Devuelve una matriz con los valores únicos en una columna específica</td>
    <td>df['columna'].unique()</td>
  </tr>
  <tr>
    <td>duplicated()</td>
    <td>Devuelve una serie booleana que indica si cada fila es duplicada o no</td>
    <td>df.duplicated()</td>
  </tr>
  <tr>
    <td>drop_duplicates()</td>
    <td>Elimina las filas duplicadas del DataFrame y devuelve el DataFrame resultante</td>
    <td>df.drop_duplicates()</td>
  </tr>
  <tr>
    <td>corr()</td>
    <td>Calcula la correlación entre columnas numéricas en el DataFrame</td>
    <td>df.corr()</td>
  </tr>
  <tr>
    <td>cov()</td>
    <td>Calcula la covarianza entre columnas numéricas en el DataFrame</td>
    <td>df.cov()</td>
  </tr>
  <tr>
    <td>min()</td>
    <td>Devuelve el valor mínimo de cada columna numérica</td>
    <td>df.min()</td>
  </tr>
  <tr>
    <td>max()</td>
    <td>Devuelve el valor máximo de cada columna numérica</td>
    <td>df.max()</td>
  </tr>
  <tr>
    <td>sum()</td>
    <td>Calcula la suma de los valores en cada columna numérica</td>
    <td>df.sum()</td>
  </tr>
  <tr>
    <td>mean()</td>
    <td>Calcula la media de los valores en cada columna numérica</td>
    <td>df.mean()</td>
  </tr>
  <tr>
    <td>median()</td>
    <td>Calcula la mediana de los valores en cada columna numérica</td>
    <td>df.median()</td>
  </tr>
  <tr>
    <td>std()</td>
    <td>Calcula la desviación estándar de los valores en cada columna numérica</td>
    <td>df.std()</td>
  </tr>
  <tr>
    <td>var()</td>
    <td>Calcula la varianza de los valores en cada columna numérica</td>
    <td>df.var()</td>
  </tr>
  <tr>
    <td>count()</td>
    <td>Calcula el número de valores no nulos en cada columna</td>
    <td>df.count()</td>
  </tr>
  <tr>
    <td>isnull()</td>
    <td>Devuelve una matriz booleana que indica qué valores son nulos</td>
    <td>df.isnull()</td>
  </tr>
  <tr>
    <td>notnull()</td>
    <td>Devuelve una matriz booleana que indica qué valores no son nulos</td>
    <td>df.notnull()</td>
  </tr>
  <tr>
    <td>astype()</td>
    <td>Convierte el tipo de datos de una o varias columnas en un tipo de datos específico</td>
    <td>df['columna'].astype('tipo')</td>
  </tr>
  <tr>
    <td>fillna()</td>
    <td>Rellena los valores faltantes (NaN) en el DataFrame con un valor específico</td>
    <td>df.fillna(valor)</td>
  </tr>
  <tr>
    <td>dropna()</td>
    <td>Elimina las filas con valores faltantes (NaN) del DataFrame y devuelve el DataFrame resultante</td>
    <td>df.dropna()</td>
  </tr>
</table>

</center>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal='.')
df
df_estilo = df.style.highlight_max(color='red', axis=0, subset=['colesterol', 'edad', 'altura','peso' ])
df_estilo

In [ ]:
df_estilo = df.style.highlight_min(color='lightcoral', axis=0, subset=['edad', 'peso', 'altura','colesterol'])
df_estilo

In [ ]:
df_estilo = df.style.format({'peso': '{:.1f}','colesterol': '{:.1f}'})
df_estilo

In [ ]:
# df_estilo = df.style.background_gradient(subset=['colesterol'], cmap='viridis')
# df_estilo = df.style.background_gradient(subset=['colesterol'], cmap='inferno')
# df_estilo = df.style.background_gradient(subset=['colesterol'], cmap='magma')
df_estilo = df.style.background_gradient(subset=['colesterol'], cmap='plasma')
df_estilo

In [ ]:
df_estilo = df.style.bar(subset=['colesterol'], color='blue')
df_estilo

In [ ]:
def resaltar_edad(fila):
    return ['background-color: yellow' if f > 30 else '' for f in fila]

df_estilo = df.style.apply(resaltar_edad, subset=['edad'])
df_estilo

In [ ]:
def highlight_max_min(s):
    es_max = s == s.max()
    es_min = s == s.min()
    return ['background-color: lightgreen' if v else 'background-color: lightcoral' if w else '' for v, w in zip(es_max, es_min)]

df_estilo = df.style.apply(highlight_max_min, subset=['colesterol'])
df_estilo

In [ ]:
df_estilo.to_html('styled_dataframe.html')

## Renombrar los nombres de las filas y columnas

Para cambiar el nombre de las filas y las columnas de un DataFrame se utiliza el siguiente método:

```python
DataFrame.rename(mapper=None, *, index=None, columns=None, axis=None, copy=True, inplace=False, level=None, errors='ignore')
```

donde

* **mapper**: Diccionario o función para aplicar a las etiquetas.

* **index**: Diccionario o función para renombrar las etiquetas de filas.

* **columns**: Diccionario o función para renombrar las etiquetas de columnas.

* **axis**: Especifica el eje para aplicar el mapeo (0 o 'index' para filas, 1 o 'columns' para columnas).

* **copy**: Si es True, se copia el DataFrame original antes de hacer las modificaciones.

* **inplace**: Si es True, hace las modificaciones en el DataFrame original sin devolver uno nuevo.

* **level**: Si el eje es un MultiIndex (índice múltiple), especifica el nivel a aplicar.

* **errors**: Controla el manejo de errores en caso de etiquetas no encontradas. Las opciones son 'ignore' y 'raise'.

Devuelve el DataFrame que resulta de renombrar las columnas indicadas en las claves del diccionario columnas con sus valores y las filas indicadas en las claves del diccionario filas con sus valores en el DataFrame df.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal=',')
nuevodf =  df.rename(columns={'nombre':'Nombre y apellidos', 'altura':'estatura'}, index={0:1000, 1:1001, 2:1002})
print(nuevodf)

### Renombrar Columnas

Para renombrar columnas, puedes usar el parámetro columns con un diccionario que mapea los nombres actuales a los nuevos nombres.

In [ ]:
import pandas as pd

# Crear un DataFrame de ejemplo
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

print("DataFrame Original:")
print(df)

# Renombrar columnas usando el método rename
df_renamed = df.rename(columns={'A': 'Alpha', 'B': 'Bravo', 'C': 'Charlie'})
print("\nDataFrame con Columnas Renombradas:")
print(df_renamed)

### Renombrar Filas

Para renombrar las etiquetas de las filas, usa el parámetro index.

In [ ]:
# Crear un DataFrame con índices específicos
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
}, index=['row1', 'row2', 'row3'])

print("\nDataFrame Original:")
print(df)

# Renombrar filas usando el método rename
df_renamed = df.rename(index={'row1': 'first', 'row2': 'second', 'row3': 'third'})
print("\nDataFrame con Filas Renombradas:")
print(df_renamed)

### Uso de `inplace`

Usar `inplace` para Modificar el DataFrame Original. El parámetro `inplace` te permite hacer los cambios directamente en el DataFrame original sin crear una copia.

In [ ]:
# Renombrar columnas en el DataFrame original
df.rename(columns={'A': 'Alpha', 'B': 'Bravo'}, inplace=True)
print("\nDataFrame Original Modificado:")
print(df)

### Renombrar Usando Funciones

Puedes usar funciones para aplicar transformaciones a las etiquetas de las columnas o filas.

In [ ]:
# Crear un DataFrame de ejemplo
df = pd.DataFrame({
    'column1': [1, 2, 3],
    'column2': [4, 5, 6]
})

print("\nDataFrame Original:")
print(df)

# Renombrar columnas usando una función
df_renamed = df.rename(columns=lambda x: x.upper())
print("\nDataFrame con Columnas Renombradas a Mayúsculas:")
print(df_renamed)

### Ejemplo

In [ ]:
import pandas as pd

# Crear un DataFrame de ejemplo
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}, index=['row1', 'row2', 'row3'])

print("DataFrame Original:")
print(df)

# Renombrar columnas
df_renamed_columns = df.rename(columns={'A': 'Alpha', 'B': 'Bravo', 'C': 'Charlie'})
print("\nDataFrame con Columnas Renombradas:")
print(df_renamed_columns)

# Renombrar filas
df_renamed_index = df.rename(index={'row1': 'first', 'row2': 'second', 'row3': 'third'})
print("\nDataFrame con Filas Renombradas:")
print(df_renamed_index)

# Renombrar usando una función para columnas
df_renamed_func = df.rename(columns=lambda x: 'Col_' + x)
print("\nDataFrame con Columnas Renombradas Usando Función:")
print(df_renamed_func)

# Renombrar in-place
df.rename(columns={'A': 'Alpha', 'B': 'Bravo'}, inplace=True)
print("\nDataFrame Original Modificado In-Place:")
print(df)

## Cambiar el índice de un DataFrame

Aunque el índice de un DataFrame suele fijarse en la creación del mismo, en ocasiones puede ser necesario cambiar el índice una vez creado el DataFrame. Para ello se utiliza el siguiente método:

<center><code>df.set_index(keys = columnas, verify_integrity = bool, drop=True, inplace=False)</code></center>

* Devuelve el `DataFrame` que resulta de eliminar las columnas de la lista columnas y convertirlas en el nuevo índice.
  
* El parámetro `verify_integrity` recibe un booleano (`False` por defecto) y realiza una comprobación para evitar duplicados en la clave cuando recibe `True`.

* `drop`: Es un valor booleano que indica si las columnas seleccionadas deben eliminarse del DataFrame. Si se establece en `True`, las columnas se eliminarán; si se establece en `False`, las columnas seleccionadas permanecerán en el DataFrame.

* `inplace`: Es un valor booleano que indica si se debe modificar el DataFrame original. Si se establece en `True`, el DataFrame original se modificará y no se devolverá un nuevo DataFrame; si se establece en `False`, se devolverá un nuevo DataFrame con el índice modificado y el DataFrame original no se verá afectado.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal=',')
df

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal=',')
df.set_index(['nombre'], inplace = True)
df

In [ ]:
df1 = df.drop('sexo', axis=1)
df2 = df1.dropna()
df2

In [ ]:
df_estilo = df2.style.highlight_max(color='red', axis=1 )
df_estilo

In [ ]:
# Definir la fila específica que quieres sombrear (por ejemplo, fila 1)
indice_fila = 'Rosa Díaz Díaz'

# Aplicar el estilo solo a la fila específica utilizando subset
df_ = df2.style.apply(lambda fila: ['background-color: yellow' if valor == fila.min() else '' for valor in fila] if fila.name == indice_fila else ['' for valor in fila], axis=1)

# Mostrar el DataFrame estilizado
df_

## Reindexar un DataFrame

Para **reordenar los índices de las filas y las columnas** de un `DataFrame`, así como añadir o eliminar índices, se utiliza el siguiente método:

```python
df.reindex(index=filas, columns=columnas, fill_value=relleno)
```

* Devuelve el `DataFrame` que resulta de tomar del DataFrame `df` las filas con nombres en la lista `filas` y las columnas con nombres en la lista `columnas`.

* `fill_value`: Especifica el valor para rellenar los elementos faltantes en el DataFrame después de la reindexación. Si alguno de los nombres indicados en filas o columnas no existía en el DataFrame `df`, se crean filan o columnas nuevas rellenas con el valor `relleno`.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal=',')
print(df.reindex(index=[4, 3, 1], columns=['nombre', 'tensión', 'colesterol', 'columna'],fill_value= 'NAN'))

## Acceso a los elementos de un DataFrame

El acceso a los datos de un DataFrame se puede hacer a través de posiciones o través de los nombres de las filas y columnas.

### Accesos mediante posiciones

```python
df.iloc[i, j]
```

Devuelve el elemento que se encuentra en la fila `i` y la columna `j` del DataFrame `df`. Pueden indicarse secuencias de índices para obtener partes del DataFrame.

```python
df.iloc[filas, columnas]
```
  
Devuelve un DataFrame con los elementos de las filas de la lista `filas` y de las columnas de la lista `columnas`.

```python
df.iloc[i]
```


Devuelve una serie con los elementos de la fila `i` del DataFrame `df`.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal=',')
print(df)

In [ ]:
print(df.iloc[1,3])

In [ ]:
print(df.iloc[:,0])

In [ ]:
print(df.iloc[5])

### Acceso a los elementos mediante nombres

```python
df.loc[fila, columna]
```


Devuelve el elemento que se encuentra en la fila con nombre `fila` y la columna de con nombre `columna` del DataFrame `df`.

```python
df.loc[filas, columnas]
```
  
Devuelve un DataFrame con los elementos que se encuentra en las filas con los nombres de la lista `filas` y las columnas con los nombres de la lista `columnas` del DataFrame `df`.

```python
df[columna]
```
  
Devuelve una serie con los elementos de la columna de nombre `columna` del DataFrame `df`.

```python
df.columna
```


Devuelve una serie con los elementos de la columna de nombre columna del DataFrame `df`. Es similar al método anterior pero **sólo funciona cuando el nombre de la columna no tiene espacios en blanco.**

In [ ]:
import pandas as pd
df = pd.read_csv('./Archivos/colesterol.csv', sep = ';',decimal=',')

In [ ]:
print(df.nombre)

In [ ]:
print(df.loc[2,'colesterol'])

In [ ]:
print(df.loc[:3,('colesterol','peso')])

In [ ]:
print(df['nombre'])

## Operaciones con las columnas de un DataFrame

### Añadir columnas a un DataFrame

El procedimiento para añadir una nueva columna a un DataFrame es similar al de añadir un nuevo par aun diccionario, pero pasando los valores de la columna en una lista o serie:

```python
df[nombre] = lista
```

Añade al DataFrame `df` una nueva columna con el nombre `nombre` y los valores de la lista `lista`. La lista debe tener el mismo tamaño que el número de filas de `df`.

```python
df[nombre] = serie
```

Añade al DataFrame `df` una nueva columna con el nombre y los valores de la serie. Si el tamaño de la serie es menor que el número de filas de `df` se rellena con valores `NaN` mientras que si es mayor se recorta.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal=',')
df['diabetes'] = pd.Series([False,False,True,False,True])
df
df['diabetess'] = pd.Series([False,False,True,False,True])
df

In [ ]:
x = 2
y = 4
print(x)
print(y)

In [ ]:
df

In [ ]:
print(df['colesterol'].sum()/12)
print(df['colesterol'].sum()/13)
print(df['colesterol'].mean())

### Operaciones sobre columnas

Puesto que los datos de una misma columna de un DataFrame son del mismo tipo, es fácil aplicar la misma operación a todos los elementos de la columna como si de una serie se tratará.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal=',')
print(df['altura']*100)
df

In [ ]:
print(df['sexo']=='M')

### Aplicar funciones a columnas

Para aplicar funciones a todos los elementos de una columna se utiliza el siguiente método

```python
df[columna].apply(f)
```


Devuelve una serie con los valores que resulta de aplicar la función `f` a los elementos de la columna con nombre columna del DataFrame `df`.

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal=',')

def f(x):
    return 2*np.exp(x)

print(df['altura'].apply(lambda x : 2*np.exp(x)))
print(df['altura'].apply(f))

### Método `pandas.to_datatime`

```python
pd.to_datetime(arg, errors='raise', dayfirst=False, yearfirst=False, utc=False, format=None, exact=True, unit=None, infer_datetime_format=False, origin='unix', cache=True)

```

* **arg**: La entrada a convertir en datetime. Puede ser una serie de pandas, un array, una lista, o un DataFrame con columnas de año, mes y día

* **format**: Una cadena de formato para especificar el formato de las fechas (por ejemplo, %d/%m/%Y).

* **errors**: Cómo manejar errores. Se tienen las siguientes opciones:
  
  * `raise`: Lanza una excepción en caso de error (comportamiento predeterminado).
  
  * `coerce`: Convierte valores no válidos en `NaT`.
  
  * `ignore`: Retorna los datos sin modificar.

* **dayfirst**: Booleano. Si `True`, se considera que el primer valor es el día (en formatos como DD/MM/YYYY)

* **yearfirst**: Booleano. Si `True`, se considera que el primer valor es el año (en formatos como YYYY/DD/MM).

#### Convertir una Serie de Fechas en String a datetime

In [ ]:
dates = pd.Series(['2024-06-01', '2024-06-02', '2024-06-03'])
dates
dates_datetime = pd.to_datetime(dates)
dates_datetime

#### Convertir una Lista de Fechas en String a datetime

In [ ]:
dates = ['2024-06-01', '2024-06-02', '2024-06-03']
dates_datetime = pd.Series(pd.to_datetime(dates))
dates_datetime

#### Manejar Diferentes Formatos de Fecha

In [ ]:
dates = pd.Series(['2024-06-01', '2024-06-02', '2024-06-03'])

dates_datetime = pd.to_datetime(dates, format='%d/%m/%Y')
print(dates_datetime)

#### Manejar Errores en la Conversión

Si tus datos contienen valores que no pueden ser convertidos a fechas, puedes manejar estos errores usando el parámetro errors

In [ ]:
dates = pd.Series(['01/05/2025', '26-01-2023', '2024-06-03'])
dates_datetime = pd.to_datetime(dates, format='%d-%m-%Y', errors='coerce')
print(dates_datetime)

#### Convertir DataFrames

In [ ]:
df = pd.DataFrame({
    'date': ['2024-06-01', '2024-06-02', '2024-06-03'],
    'value': [10, 20, 30]
})


df['date'] = pd.to_datetime(df['date'])
print(df)

#### Conversión de Columnas Separadas a datetime

Si tus datos de fecha están en columnas separadas (por ejemplo, año, mes, día), puedes combinarlos usando to_datetime.

In [ ]:
df = pd.DataFrame({
    'year': [2024, 2024, 2024],
    'month': [6, 6, 6],
    'day': [1, 2, 3]
})
# df

df['Fecha'] = pd.to_datetime(df[['year', 'month', 'day']])
df

### Convertir una columna al tipo datetime

A menudo una columna contiene cadenas que representan fechas. Para convertir estas cadenas al tipo datetime se utiliza el siguiente método:

```python
to_datetime(columna, formato)
```

Devuelve la serie que resulta de convertir las cadenas de la `columna` con el nombre `columna` en fechas del tipo `datetime` con el formado especificado en `formato`.

In [ ]:
import pandas as pd

df=pd.DataFrame({'Nombre':['María','Carlos','Carmen'],'Nacimiento':['05-03-2000', '20-05-2001', '10-12-1999']})
print(df.Nacimiento)

In [ ]:
df['Nacimiento'] = pd.to_datetime(df.Nacimiento,format='%d-%m-%Y')
# print(pd.to_datetime(df.Nacimiento,format='%d-%m-%Y'))
print(df.Nacimiento)

In [ ]:
df

### Resumen descriptivo de un DataFrame

Al igual que para las series, los siguientes métodos permiten resumir la información de un DataFrame por columnas:

* `df.count()`: Devuelve una serie con el número de elementos que no son nulos ni `NaN` en cada columna del DataFrame `df`.

* `df.sum()`: Devuelve una serie con la suma de los datos de las columnas del DataFrame `df` cuando los datos son de un tipo numérico, o la concatenación de ellos cuando son del tipo cadena `str`.

* `df.cumsum()`: Devuelve un DataFrame con la suma acumulada de los datos de las columnas del DataFrame `df` cuando los datos son de un tipo numérico.
  
* `df.min()`: Devuelve una serie con los menores de los datos de las columnas del DataFrame `df`.

* `df.max()`: Devuelve una serie con los mayores de los datos de las columnas del DataFrame `df`.

* `df.mean()`: Devuelve una serie con las medias de los datos de las columnas numéricas del DataFrame `df`.

* `df.var()`: Devuelve una serie con las varianzas de los datos de las columnas numéricas del DataFrame `df`.

* `df.std()`: Devuelve una serie con las desviaciones típicas de los datos de las columnas numéricas del DataFrame `df`.

* `df.cov()`: Devuelve un DataFrame con las covarianzas de los datos de las columnas numéricas del DataFrame `df`.

* `df.corr()`: Devuelve un DataFrame con los coeficientes de correlación de Pearson de los datos de las columnas numéricas del DataFrame `df`.
  
* `df.describe(include = tipo)`: Devuelve un DataFrame con un resumen estadístico de las columnas del DataFrame `df` del tipo tipo. Para los datos numéricos (`number`) se calcula la media, la desviación típica, el mínimo, el máximo y los cuartiles. Para los datos no numéricos (`object`) se calcula el número de valores, el número de valores distintos, la moda y su frecuencia. Si no se indica el tipo solo se consideran las columnas numéricas

In [ ]:
import os
print("Directorio de trabajo actual:", os.getcwd())

In [ ]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal=',')
df['diabetes'] = pd.Series([False,False,True,False,True])
df

In [ ]:
df.count()

In [ ]:
(df['sexo']=='M').count()

In [ ]:
print([x for x in df['sexo'] if x=='M'])
len([x for x in df['sexo'] if x=='M'])

In [ ]:
df['sexo'].istrue.sum()

In [ ]:
df.sum()

In [ ]:
df.diabetes.isnull().sum()

In [ ]:
print(df.edad.mean())

In [ ]:
print(df.edad.var())

In [ ]:
print(df.edad.std())

In [ ]:
df.edad.cov()

In [ ]:
df.corr()

In [ ]:
print(df.describe())

In [ ]:
print(df.describe(include='object'))

**Observaión:** Al utilizar el parámetro `include='object'` en el método `describe()`, se generará un resumen estadístico de las columnas de tipo objeto (cadenas de texto) en el data frame. Esto te proporcionará información descriptiva sobre estas columnas.

El resultado será un nuevo data frame que contiene la siguiente información para cada columna de tipo objeto:

* `count`: el número de valores no nulos en la columna.

* `unique`: el número de valores únicos en la columna.

* `top`: el valor más frecuente en la columna.

* `freq`: la frecuencia del valor más frecuente en la columna.

### Eliminar columnas de un DataFrame

Para eliminar columnas de un DataFrame se utilizan los siguientes métodos:

```python
del d[nombre]
```

Elimina la columna con nombre nombre del DataFrame df.

```python  
df.pop(nombre)
```

Elimina la columna con nombre nombre del DataFrame df y la devuelve como una serie.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal=',')
df

In [ ]:
df.pop('diabetes')
df

In [ ]:
del df['colesterol']

In [ ]:
del df['sexo']
df

## Operaciones con las filas de un DataFrame

### Añadir una fila a un DataFrame


Para añadir una fila a un DataFrame se utiliza el siguiente método:

```python
df.append(serie, ignore_index=True)
```

Devuelve el DataFrame que resulta de añadir una fila al DataFrame `df` con los valores de la serie `serie`. Los nombres del índice de la serie deben corresponderse con los nombres de las columnas de `df`. Si no se pasa el parámetro `ignore_index` entonces debe pasarse el parámetro `name` a la serie, donde su argumento será el nombre de la nueva fila.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal=',')
df

In [ ]:
serie = pd.Series(['Carlos Rivas', 28, 'H', 89.0, 1.78, 245.0], index=['nombre','edad','sexo','peso','altura','colesterol'])
serie

In [ ]:
df = df.append(serie, ignore_index=True)
# print(df.tail())
df

# The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
# df = df.append(serie, ignore_index=True)

### Eliminar filas de un DataFrame

Para eliminar filas de un DataFrame se utilizan el siguiente método:

```python
df.drop(filas)
```

Devuelve el DataFrame que resulta de eliminar las `filas` con los nombres indicados en la lista filas del DataFrame `df`.

In [ ]:
df_resultante = df.drop([0,1])
df_resultante

### Filtrar las filas de un DataFrame

Una operación bastante común con un DataFrame es obtener las filas que cumplen una determinada condición.

```python
df[condicion]
```

Devuelve un DataFrame con las filas del DataFrame `df` que corresponden con el valor `True` de la lista booleana `condicion`. `condicion` debe ser una lista de valores booleanos de la misma longitud que el número de filas del DataFrame.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal=',')

In [ ]:
condicion = (df['sexo']=='H') & (df['colesterol'] > 278)
condicion

In [ ]:
print(df[condicion])

### Ordenar un DataFrame


Para ordenar un DataFrame de acuerdo a los valores de una determinada columna se utilizan los siguientes métodos:

```python
df.sort_values(columna, ascending=booleano)
```

Devuelve el DataFrame que resulta de ordenar las filas del DataFrame `df` según los valores del la columna con nombre columna. Si argumento del parámetro `ascending` es `True` el orden es creciente y  decreciente si es `False` .

```python
df.sort_index(ascending=booleano)
```

Devuelve el DataFrame que resulta de ordenar las filas del DataFrame `df` según los nombres de las filas. Si el argumento del parámetro `ascending` es `True` el orden es creciente y  decreciente si es `False`.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal=',')
df = df.dropna()
print(df.sort_values('colesterol'))

### Fusionar datos de Dataframes distintos: `pandas.concat()`

El método `concat` en pandas se utiliza para concatenar pandas `objects` como Series y DataFrames a lo largo de un eje (axis).

La sintaxis general es:

```python
pandas.concat(objs, axis=0, join='outer', ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, sort=False, copy=True)
```

* **objs**: Una lista o diccionario de objetos pandas (Series o DataFrame) que se desea concatenar.

* **axis**: Eje a lo largo del cual concatenar. `0` para concatenar por filas, `1` para concatenar por columnas. El valor predeterminado es `0`.

* **join**: Tipo de unión. Puede ser `inner` o `outer`. El valor predeterminado es `outer`.

* **ignore_index**: Si se debe ignorar el índice del eje de concatenación. El valor predeterminado es `False`.
  
* **keys**: Secuencia para usar como jerarquía de los niveles en el índice del eje resultante.

* **sort**: Ordenar columnas si el eje es `1`. No es necesario si las columnas ya están ordenadas. El valor predeterminado es `False`.

### Concatenar DataFrames por Filas (`axis=0`):

In [6]:
import pandas as pd

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'], 'B': ['B0', 'B1', 'B2']})
df2 = pd.DataFrame({'A': ['A3', 'A4', 'A5'], 'B': ['B3', 'B4', 'B5']})

print(df1)
print(df2)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
    A   B
0  A3  B3
1  A4  B4
2  A5  B5

In [3]:
resultado = pd.concat([df1, df2])
print(resultado)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
0  A3  B3
1  A4  B4
2  A5  B5

### Concatenar DataFrames por Columnas (`axis=1`):

In [4]:
result = pd.concat([df1, df2], axis=1)
print(result)

    A   B   A   B
0  A0  B0  A3  B3
1  A1  B1  A4  B4
2  A2  B2  A5  B5

### Concatenar y Ignorar el Índice:

In [7]:
result = pd.concat([df1, df2], ignore_index=True)
print(result)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4
5  A5  B5

### Concatenar con Unión Interna (`inner join`):

In [8]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'], 'B': ['B0', 'B1', 'B2']})
df2 = pd.DataFrame({'B': ['B3', 'B4', 'B5'], 'C': ['C3', 'C4', 'C5']})

result = pd.concat([df1, df2])
print(result)

     A   B    C
0   A0  B0  NaN
1   A1  B1  NaN
2   A2  B2  NaN
0  NaN  B3   C3
1  NaN  B4   C4
2  NaN  B5   C5

In [10]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'], 'B': ['B0', 'B1', 'B2'], 'Z': ['Z0', 'Z1', 'Z2']})
df2 = pd.DataFrame({'B': ['B3', 'B4', 'B5'], 'A': ['C3', 'C4', 'C5']})

result = pd.concat([df1, df2], join='inner')
print(result)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
0  C3  B3
1  C4  B4
2  C5  B5

### Concatenar con Claves:

In [11]:
import pandas as pd
resultado = pd.concat([df1, df2], keys=['Dataframe1', 'Dataframe2'])
print(resultado)

               A   B    Z
Dataframe1 0  A0  B0   Z0
           1  A1  B1   Z1
           2  A2  B2   Z2
Dataframe2 0  C3  B3  NaN
           1  C4  B4  NaN
           2  C5  B5  NaN

### Observaciones

* `verify_integrity`: Si se establece en `True`, la función verificará si hay duplicados en los índices y lanzará un error en caso de que existan.
  
* `sort`: En operaciones de unión interna, el argumento `sort=True` puede ser útil para ordenar las columnas alfabéticamente.

In [12]:
import pandas as pd
resultado = pd.concat([df1, df2], verify_integrity=True)
print(resultado)

ValueError: Indexes have overlapping values: Index([0, 1, 2], dtype='int64')

In [13]:
import pandas as pd

resultado = pd.concat([df1, df2], keys=['Dataframe1', 'Dataframe2'], verify_integrity=True)
print(resultado)

               A   B    Z
Dataframe1 0  A0  B0   Z0
           1  A1  B1   Z1
           2  A2  B2   Z2
Dataframe2 0  C3  B3  NaN
           1  C4  B4  NaN
           2  C5  B5  NaN

In [14]:
import pandas as pd

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'], 'Z': ['B9', 'B0', 'B2']})
df2 = pd.DataFrame({'Z': ['B3', 'B4', 'B5'], 'A': ['C3', 'C4', 'C5']})

resultado = pd.concat([df1, df2], join = 'inner', sort=True, ignore_index=True)
print(resultado)

    A   Z
0  A0  B9
1  A1  B0
2  A2  B2
3  C3  B3
4  C4  B4
5  C5  B5

### Ejemplo

In [15]:
import numpy as np

df_a = pd.DataFrame(np.random.randn(5,2))
df_b = pd.DataFrame(np.random.randn(5,2))

pd.concat([df_a, df_b], axis=0)

          0         1
0  2.418049 -0.149188
1 -0.820633  1.622484
2  0.860733  0.332273
3  0.178576  0.548975
4  1.461052 -0.023454
0  1.751859  0.046034
1 -0.251860 -1.190833
2 -0.079814  2.234881
3  1.295682 -0.506915
4 -0.767527 -1.777871

In [20]:
import pandas as pd
import numpy as np

def f(x):
    return x**2 + 1
n = 5

x_valores = pd.DataFrame(range(-n,n+1), columns=['x'])
x_valores


f_valores = (x_valores.apply(f)).rename(columns = {'x':'f(x)'})
f_valores

tabla = pd.concat([x_valores, f_valores], axis = 1)
tabla

    x  f(x)
0  -5    26
1  -4    17
2  -3    10
3  -2     5
4  -1     2
5   0     1
6   1     2
7   2     5
8   3    10
9   4    17
10  5    26

## Eliminar las filas con dados desconocidos en un DataFrame


Para eliminar las filas de un DataFrame que contienen datos desconocidos `NaN` o nulos `None` se utiliza el siguiente método:

```python
df.dropna(subset=columnas)
```

Devuelve el DataFrame que resulta de eliminar las filas que contienen algún dato desconocido o nulo en las columnas de la lista `columna` del DataFrame `df`. Si no se pasa un argumento al parámetro `subset` se aplica a todas las columnas del DataFrame.

In [23]:
import pandas as pd
df = pd.read_csv('/content/colesterol.csv', sep = ';',decimal=',')
df

                             nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [25]:
# print(df.sort_values('colesterol'))
print(df.dropna(subset =['peso','colesterol'] ))

                             nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

## `dataframe.data_range`

El método `date_range` de pandas es una función muy útil para **generar una serie de fechas en un rango específico con una frecuencia determinada**. Este método es comúnmente usado en análisis de datos para crear índices de fechas y generar secuencias de fechas para simulaciones, análisis financieros, y otros tipos de análisis temporales.

La sintaxis general del método `data_range` es:

```python
pd.date_range(start=None, end=None, periods=None, freq='D', tz=None, normalize=False, name=None, closed=None, **kwargs)
```
donde
* **start**: La fecha de inicio del rango. Puede ser una cadena, `datetime`, o `Timestamp`.

* **end**: La fecha de finalización del rango. Similarmente, puede ser una `cadena`, `datetime`, o `Timestamp`.

* **periods**: Número de periodos a generar. Exclusivo con los parámetros `start` y `end`.

* **freq**: Frecuencia de los periodos. Los más comunes son:

  * **'D'**: Día (por defecto).

  * **'B'**: Día hábil.

  * **'H'**: Hora.

  * **'T'** o **'min'**: Minuto.

  * **'S'**: Segundo.

  * **'A'** o **'Y'**: Año fin de período.

  * **'W'**: Semana.

  * **'M'**: Mes fin de período


<!--
* .

* **'MS'**: Mes inicio de período. -->


<!-- * **'AS'** o **'YS'**: Año inicio de período. -->

<!-- * **'Q'**: Trimestre fin de período. -->

<!-- * **'QS'**: Trimestre inicio de período. -->


* **name**: Nombre de la serie resultante.

In [27]:
import pandas as pd

rango_fechas = pd.date_range(start='2023-01-01', end='2023-01-10')
print(pd.DataFrame(rango_fechas))

           0
0 2023-01-01
1 2023-01-02
2 2023-01-03
3 2023-01-04
4 2023-01-05
5 2023-01-06
6 2023-01-07
7 2023-01-08
8 2023-01-09
9 2023-01-10

In [28]:
rango_fechas = pd.date_range(start='2023-01-01', periods=6, freq='M')
print(pd.Series(rango_fechas))

0   2023-01-31
1   2023-02-28
2   2023-03-31
3   2023-04-30
4   2023-05-31
5   2023-06-30
dtype: datetime64[ns]

In [29]:
rango_fechas = pd.date_range(start='2023-01-01', periods=10, freq='H')
print(pd.Series(rango_fechas))

0   2023-01-01 00:00:00
1   2023-01-01 01:00:00
2   2023-01-01 02:00:00
3   2023-01-01 03:00:00
4   2023-01-01 04:00:00
5   2023-01-01 05:00:00
6   2023-01-01 06:00:00
7   2023-01-01 07:00:00
8   2023-01-01 08:00:00
9   2023-01-01 09:00:00
dtype: datetime64[ns]

### Ejemplo

In [ ]:
import numpy as np

fechas = pd.date_range('20200101', periods=6)

df = pd.DataFrame(np.random.randn(6, 4), index=fechas, columns=list('ABCD'))

df

## `pandas.Timestamp`

El método `Timestamp` en pandas es una clase que **representa un sólo punto en el tiempo**, similar a un objeto datetime en Python pero con mayor funcionalidad y optimización para su uso en análisis de datos.

### Creación de un `Timestamp`

Puedes crear un `Timestamp` de varias maneras:

#### Desde una cadena de fecha y hora:

In [ ]:
import pandas as pd

ts = pd.Timestamp('2023-05-27')
print(ts)

#### Desde componentes individuales (año, mes, día, hora, minuto, segundo.):

In [ ]:
ts = pd.Timestamp(2023, 5, 27, 10, 30, 45)
print(ts)

#### Desde un objeto datetime de Python:

In [ ]:
from datetime import datetime

dt = datetime(2023, 5, 27, 10, 30, 45)
print('dt = ', dt)
ts = pd.Timestamp(dt)
print(ts)

## Propiedades y Métodos de Timestamp

### Propiedades

In [ ]:
ts = pd.Timestamp('2023-05-27 10:30:45')
print("Año:", ts.year)
print("Mes:", ts.month)
print("Día:", ts.day)
print("Hora:", ts.hour)
print("Minuto:", ts.minute)
print("Segundo:", ts.second)
print("Día de la semana:", ts.dayofweek)  # Lunes=0, Domingo=6
print("Nombre del día de la semana:", ts.day_name())  # Nombre del día en inglés :(

### Algunos **métodos**

Ajustar el tiempo a la medianoche

In [ ]:
ts_midnight = ts.normalize()
print("Medianoche:", ts_midnight)

#### Convertir a otra zona horaria

In [ ]:
ts_utc = ts.tz_localize('UTC')
print("Zona horaria UTC:", ts_utc)

#### Convertir a una zona horaria diferente

In [ ]:
ts_pacific = ts_utc.tz_convert('US/Pacific')
print("Zona horaria Pacífico:", ts_pacific)

## Operaciones con Timestamp

### Comparación de fechas y horas:

In [ ]:
ts1 = pd.Timestamp('2023-05-27 10:30:45')
ts2 = pd.Timestamp('2023-05-28 10:30:45')

print("ts1 es antes de ts2:", ts1 < ts2)
print("ts1 es igual a ts2:", ts1 == ts2)
print("ts1 es después de ts2:", ts1 > ts2)

## Ejemplo

In [ ]:
dates = pd.date_range('2023-01-01', periods=5, freq='D')
data = [1, 2, 3, 4, 5]
series = pd.Series(data, index=dates)
print(series)

## `pandas.Categorical`

El método `Categorical` en pandas se utiliza para trabajar con datos categóricos, que son datos que pueden tomar un número limitado y generalmente fijo de posibles valores (categorías). Los datos categóricos se pueden utilizar para realizar operaciones más eficientes y ahorrar memoria, ya que en lugar de almacenar cada valor repetidamente, solo se almacenan referencias a las categorías.

## Creación de Datos Categóricos

Puedes crear datos categóricos de varias maneras:

### Convertir una Serie existente a datos categóricos:

In [ ]:
import pandas as pd

serie = pd.Series(['manzana', 'pera', 'manzana', 'naranja', 'pera'])
serie_categorica = serie.astype('category')
print(serie_categorica)

### Crear una Serie categórica directamente:

In [ ]:
import pandas as pd

serie_categorica = pd.Categorical(['manzana', 'pera', 'manzana', 'naranja', 'pera'])
print(serie_categorica)

### Crear una Serie categórica con categorías específicas y ordenadas:

In [ ]:
import pandas as pd

serie_categorica = pd.Categorical(['manzana', 'pera', 'manzana', 'naranja', 'pera'],
                               categories=['naranja', 'pera', 'manzana'],
                               ordered=True)
print(serie_categorica)

## Propiedades y Métodos de los Datos Categóricos

Los datos categóricos tienen varias propiedades y métodos útiles:

* **categories**: Devuelve las categorías.
  
* **codes**: Devuelve los códigos de las categorías.
  
* **ordered**: Indica si las categorías tienen un orden.

In [ ]:
print("Categorías:", serie_categorica.categories)
print("Códigos:", serie_categorica.codes)
print("Ordenado:", serie_categorica.ordered)

## Operaciones con Datos Categóricos

### Comparación:

In [ ]:
print(serie_categorica > 'pera')

### Agrupación:

In [ ]:
df = pd.DataFrame({
    'frutas': ['manzana', 'pera', 'manzana', 'naranja', 'pera'],
    'cantidad': [10, 5, 8, 12, 7]
})
df['frutas'] = df['frutas'].astype('category')
grouped = df.groupby('frutas').sum()
print(grouped)

### Conteo de valores:

In [ ]:
print(serie_categorica.value_counts())

## Ejemplo

In [ ]:
import pandas as pd

# Crear una Serie categórica
frutas = pd.Series(['manzana', 'pera', 'manzana', 'naranja', 'pera'])
frutas_categorical = frutas.astype('category')
print("Serie categórica:")
print(frutas_categorical)

# Propiedades de los datos categóricos
print("\nCategorías:", frutas_categorical.cat.categories)
print("Códigos:", frutas_categorical.cat.codes)
print("Ordenado:", frutas_categorical.cat.ordered)

# Crear una Serie categórica ordenada
frutas_categorical_ordered = pd.Categorical(['manzana', 'pera', 'manzana', 'naranja', 'pera'],
                                            categories=['naranja', 'pera', 'manzana'],
                                            ordered=True)
print("\nSerie categórica ordenada:")
print(frutas_categorical_ordered)

# Comparación
print("\nComparación (mayor que 'pera'):")
print(frutas_categorical_ordered > 'pera')

# Agrupación
df = pd.DataFrame({
    'frutas': ['manzana', 'pera', 'manzana', 'naranja', 'pera'],
    'cantidad': [10, 5, 8, 12, 7]
})
df['frutas'] = df['frutas'].astype('category')
grouped = df.groupby('frutas').sum()
print("\nAgrupación por categoría:")
print(grouped)

# Conteo de valores
print("\nConteo de valores:")
print(frutas_categorical.value_counts())

## Ejemplo con distintos tipos de datos

Como en las `Series`, los `DataFrame` pueden utilizar diferentes tipos de datos en cada columna y asignarse como diccionarios.

In [ ]:
df = pd.DataFrame({'A': 1.,
                   'B': pd.Timestamp('20200101'),
                   'C': pd.Series(1, index=list(range(4))),
                   'D': np.array([3] * 4, dtype='int32'),
                   'E': pd.Categorical(['norte', 'sur', 'este', 'oeste']),
                   'F': 'hola'
                  })

df

## Convertir DataFrame a NumPy

Cuando sea deseable, se puede transformar el `DataFrame` a un `array` de NumPy.

In [ ]:
df.to_numpy()

Lo anterior tanto si el `DataFrame` tiene un solo tipo o diversos tipos de datos.

### Ejemplo de manipulación para un solo tipo de datos

Si todos los elementos son del mismo tipo, se pueden ejecutar algunas funciones de análisis y manipulación específicas, especialmente si son datos numéricos.

A continuación se crea un `DataFrame` tipo matriz 6$\times$4 de números aleatorios.

In [ ]:
df_num = pd.DataFrame(np.random.randn(6, 4), columns=list("ABCD"), index=['a', 'b', 'c', 'd', 'e', 'f'])

df_num

Es posible obtener un resumen de los principales descriptores estadísticos de cada columna, en este caso: el conteo de elementos, la media, la desviación estándar, el valor mínimo, el primer, segundo y tercer cuartil, y el valor máximo.

In [ ]:
df_num.describe()

##### Reordenar datos

Es común desear reordenar los datos con alguna columna de referencia:

In [ ]:
df_num.sort_values(by='B')

## `Dataframe.groupby `

El método `groupby` en pandas se utiliza para agrupar datos en un DataFrame según uno o más criterios. Esto permite realizar operaciones de agregación, transformación y filtrado en grupos de datos.

```python
DataFrame.groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False, observed=False, dropna=True)
```

donde

* **by**: Criterios para agrupar los datos. Puede ser una columna, una lista de columnas, una función, un dict, una Series, etc.
  
* **axis**: Eje a lo largo del cual se agrupan los datos. El valor predeterminado es 0 (filas).

* **level**: Si el índice es jerárquico (MultiIndex), agrupa por uno o más niveles.

* **as_index**: Si es True, los valores agrupados se utilizan como el índice del resultado. El valor predeterminado es True.

* **sort**: Si es True, los grupos se ordenan por sus etiquetas. El valor predeterminado es True.

* **group_keys**: Si es True, los keys de grupo se incluyen en el índice del resultado. El valor predeterminado es True.

### Agrupar por una Columna y Calcular la Media

In [ ]:
import pandas as pd

data = {
    'Equipo': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Puntos': [10, 20, 15, 25, 10, 30]
}
df = pd.DataFrame(data)

group = df.groupby('Equipo')
print(group.mean())

### Agrupar por Múltiples Columnas

In [ ]:
data = {
    'Equipo': ['A', 'A', 'B', 'B', 'A', 'A'],
    'Jugador': ['K1', 'K2', 'K1', 'K2', 'K1', 'K2'],
    'Puntos': [5, 10, 15, 20, 25, 30]
}
df = pd.DataFrame(data)

group = df.groupby(['Equipo', 'Jugador'])
print(group.sum())

### Aplicar Funciones de Agregación Personalizadas

In [ ]:
def rango(x):
    return x.max() - x.min()

group = df.groupby('Equipo')
print(group.agg(rango))

### Filtrar Grupos

In [ ]:
def filtro(x):
    return x['Puntos'].mean() > 20

group = df.groupby('Equipo').filter(filtro)
print(group)

### Transformar Grupos

In [ ]:
df['Media_Puntos'] = df.groupby('Equipo')['Puntos'].transform('mean')
print(df)

### Aplicar Funciones a Grupos y Expandir el Resultado

In [ ]:
def sumar_puntos(grupo):
    return grupo.assign(Total=grupo['Puntos'].sum())

group = df.groupby('Equipo').apply(sumar_puntos)
print(group)